{% set name = "biogeme-optimization" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/biogeme_optimization-{{ version }}.tar.gz
  sha256: a4e964d034208eb762217556112369d9f8f7dfeabe603a2dde360bca50031fca
  patches:
    - pyproject.toml.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=63.4.1
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy >=1.14.0
    - matplotlib-base >=3.8.4
    - tomlkit >=0.12.5

test:
  imports:
    - biogeme_optimization
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://biogeme.epfl.ch
  summary: Various optimization algorithms for teaching and research
  license: LicenseRef-BIOGEME-OPTIMIZATION
  license_file: LICENSE
  dev_url: https://github.com/michelbierlaire/optimization

extra:
  recipe-maintainers:
    - FGarridoV
    - sandervancranenburgh
