{% set name = "biogeme-optimization" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/biogeme_optimization-{{ version }}.tar.gz
  sha256: 1d503fdd227162d9bf74f4290e66ff01a314c97793983fb73c84e49855b5445d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - setuptools >=63.4.1
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy >=1.14.0
    - matplotlib-base >=3.8.4
    - tomlkit >=0.12.5

test:
  imports:
    - biogeme_optimization
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://biogeme.epfl.ch
  summary: Various optimization algorithms for teaching and research
  license: LicenseRef-BIOGEME-OPTIMIZATION
  license_file: LICENSE
  dev_url: https://github.com/michelbierlaire/optimization

extra:
  recipe-maintainers:
    - FGarridoV
    - sandervancranenburgh
